### ISSUE TITLE
Camera export from Unity to Blender

### ISSUE THREAD

**Issue by mshooter** [emilianavt/BVHTools#16]
Hi, 
Thank you for the tool :) 

you were able to export the bvh file for Blender. 
However, could you explain how you would export the position and rotation of the camera in unity to blender?

**Comment by emilianavt** [comment]
Hi! BVH files can only contain the bone hierarchy of a model. Exporting the camera is not directly supported. If the camera is parented to a bone in the model, it may be possible to record those bones however and perhaps somehow link the Blender camera to that bone.

**Comment by mshooter** [comment]
Hi thank you for answering. 
I meant would you know the math for converting the camera from Unity (left hand coordinate system) to blender (right hand coordinate system) ? 
As I tried to do it based on your calculations but it doesn’t work for me.. unfortunately.

**Comment by emilianavt** [comment]
I see. Sadly it's been a bit too long for me to remember the details of how the calculations work, I'm sorry.

If following the calculations in the code doesn't produce the correct results, you may have to also look into Blender's BVH importer, since [importing](https://github.com/emilianavt/BVHTools#editing) the file relies on certain settings, so additional transformations may be needed, beyond what the BVH Tools code does.

**Comment by mshooter** [comment]
Ok thank you☺️
