### ISSUE TITLE
BVHTools v1.4.3 --- no animator found

### ISSUE THREAD

**Issue by kavinever** [emilianavt/BVHTools#5]
Great tool.
Hi, I stumble into this problem, in TARGET AVATAR entry, I can't find any animator despite I have several. I'm quite new to unity3D, to my limited knowledge, is it related to the Unity3D version(I'm using 2018.4.6), or have I made some stupid mistakes?

**Comment by emilianavt** [comment]
Hi, I somehow missed when this issue was posted.
Your Unity version should be fine. If you add the BVHRecorder component to the same component as your Animator, it should set the target avatar automatically in current versions of BVHTools. If this doesn't work, please check if the rig is set to humanoid and the Animator has an avatar set.
